import Head from "next/head";
import Image from "next/image";
import heroBg from "../../public/images/hero-bg.png";
import blupayDashboard from "../../public/images/User dashboard - Overview.png";
import ReachOutToUs from "@/components/ReachOutToUs";
import JoinWaitlistForm from "@/forms/JoinWaitlistForm";
import LaunchNotice from "@/components/LaunchNotice";
import FAQSection from "@/components/FAQSection";
import AvailableGlobally from "@/components/AvailableGlobally";
import BluPayFeatures from "@/components/BluPayFeatures";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import { Fade, Bounce } from "react-reveal";
import {
  FaCaretDown,
  FaCaretSquareDown,
  FaRegCaretSquareDown,
} from "react-icons/fa";
import { useEffect, useRef } from "react";
import alert1 from "../../public/images/alert-1.svg";
import alert2 from "../../public/images/alert-2.svg";

export default function Home() {
  const scrollRef = useRef(null);

  const scrollDown = () => {
    window.scrollTo({
      top: scrollRef.current.offsetTop - 120,
      behavior: "smooth",
    });
  };

  return (
    <>
      <Head>
        <title>
          BluPay Finance | Easy and Secure way to send and receive crypto
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Layout bg={heroBg} homeBg={true}>
          {/* HERO SECTION */}
          <section className="text-center relative text-white mt-40 p-10">
            {/* HEADING */}
            <div>
              <Fade up duration={1000} delay={900}>
                <Image
                  src={alert1}
                  alt="Credit alert"
                  className="w-80 relative -top-12 -right-12 lg:-right-96 md:w-96"
                />
              </Fade>
              <Fade up duration={800}>
                <h2 className="text-2xl md:text-4xl lg:text-4.5xl font-semibold hero-headers">
                  An <span className="text-blupayGreen">easy</span> and{" "}
                  <span className="text-blupayGreen">secure</span> way for
                </h2>
              </Fade>
              <Fade up duration={800} delay={200}>
                <h1 className="text-blupayGreen text-5xl md:text-6xl lg:text-7xl mt-2 font-extrabold">
                  Everyone
                </h1>
              </Fade>

              <Fade duration={800} delay={300}>
                <h1 className="text-2xl md:text-4xl md:md-14 lg:text-4.5xl mt-2 font-semibold">
                  to get paid in crypto.
                </h1>
              </Fade>

              <Fade duration={600} delay={300}>
                <p className="text-sm md:text-lg lg:max-w-2xl font-normal mt-10 md:my-14 max-w-lg mx-auto">
                  Send and receive crypto payments from friends, family and
                  clients all over the world without the hassle of owning a
                  crypto wallet.
                </p>
              </Fade>

              <Fade up duration={1000} delay={600}>
                <Image
                  src={alert2}
                  alt="Credit alert"
                  className="w-80 z-8 absolute -bottom-72 right-0 md:w-96 md:-bottom-44 lg:-bottom-5 lg:right-32"
                />
              </Fade>
            </div>

            {/* JOIN WAITLIST */}
            <div className="mt-10 relative z-10 md:my-14">
              <Fade duration={600} delay={300}>
                <JoinWaitlistForm />
              </Fade>
            </div>

            <div className="flex justify-center w-full mt-36 animate-bounce lg:hidden">
              <Fade duration={800} delay={1000}>
                <FaCaretDown
                  size={35}
                  style={{
                    padding: "4px",
                    borderWidth: "1px",
                    borderRadius: "50%",
                    cursor: "pointer",
                  }}
                  onClick={scrollDown}
                />
              </Fade>
            </div>
          </section>

          <section className="bg-white" ref={scrollRef}>
            {/* INTERSECTING PICTURE */}
            <div className="w-full hidden text-center lg:flex md:hidden justify-center px-40 mt-52 sm:px-60">
              <Fade up duration={600} delay={0}>
                <Image
                  src={blupayDashboard}
                  alt="Easily send and receive crypto with BluPay"
                  className="shadow-lg max-w-6xl mx-auto xl:max-w-6xl lg:max-w-5xl md:block sm:hidden -mt-48"
                />
              </Fade>
            </div>

            {/* BLUPAY FEATURES */}
            <BluPayFeatures />

            {/* BLUPAY IS AVAILABLE GLOBALLY */}
            <AvailableGlobally />

            {/* GOT QUESTIONS? */}
            <div className="-mt-32 mb-30">
              <FAQSection />
            </div>

            {/* BE THE FIRST TO KNOW WHEN WE LAUNCH */}
            <LaunchNotice />

            {/* CONTACT US */}
            <ReachOutToUs />

            {/* FOOTER */}
            <Footer />
          </section>
        </Layout>
      </body>
    </>
  );
}
