import Head from "next/head";
import Image from "next/image";
import heroBg from "../../public/images/hero-bg.png";
import blupayDashboard from "../../public/images/User dashboard - Overview.png";
import ReachOutToUs from "@/components/ReachOutToUs";
import JoinWaitlistForm from "@/forms/JoinWaitlistForm";
import LaunchNotice from "@/components/LaunchNotice";
import FAQSection from "@/components/FAQSection";
import AvailableGlobally from "@/components/AvailableGlobally";
import BluPayFeatures from "@/components/BluPayFeatures";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          BluPay Finance | Easy and Secure way to send and receive crypto
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout bg={heroBg} homeBg={true}>
        {/* HERO SECTION */}
        <section className="text-center text-white mt-20 p-10">
          {/* HEADING */}
          <div>
            <h2 className="text-3xl md:text-4xl lg:text-4.5xl font-bold hero-headers">
              An <span className="text-blupayGreen">easy</span> and{" "}
              <span className="text-blupayGreen">secure</span> way for
            </h2>
            <h1 className="text-blupayGreen text-5xl md:text-6xl lg:text-7xl mt-2 font-extrabold">
              Everyone
            </h1>
            <h1 className="text-3xl md:text-4xl md:md-14 lg:text-4.5xl mt-2 font-bold">
              to get paid in crypto.
            </h1>

            <p className="text-sm md:text-lg lg:max-w-2xl font-normal mt-10 md:my-14 max-w-lg mx-auto">
              Send and receive crypto payments from friends, family and clients
              all over the world without the hassle of owning a crypto wallet.
            </p>
          </div>

          {/* JOIN WAITLIST */}
          <div className="mt-10 md:my-14">
            <JoinWaitlistForm />
          </div>
        </section>

        {/* INTERSECTING PICTURE */}
        <div className="w-full hidden text-center lg:flex md:hidden justify-center px-40 mt-32 sm:px-60">
          <Image
            src={blupayDashboard}
            alt="Easily send and receive crypto with BluPay"
            className="shadow-lg max-w-6xl mx-auto xl:max-w-6xl lg:max-w-5xl md:block sm:hidden"
          />
        </div>

        {/* BLUPAY FEATURES */}
        <BluPayFeatures />

        {/* BLUPAY IS AVAILABLE GLOBALLY */}
        <AvailableGlobally />

        {/* GOT QUESTIONS? */}
        <FAQSection />

        {/* BE THE FIRST TO KNOW WHEN WE LAUNCH */}
        <LaunchNotice />

        {/* CONTACT US */}
        <ReachOutToUs />

        {/* FOOTER */}
        <Footer />
      </Layout>
    </>
  );
}
